"""Delete tables and created_at and updated_at to Characters table

Revision ID: 0b4ebed337ae
Revises: 
Create Date: 2025-05-15 23:39:57.952918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4ebed337ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enemy_characters_character_name', table_name='enemy_characters')
    op.drop_index('ix_enemy_characters_id', table_name='enemy_characters')
    op.drop_table('enemy_characters')
    op.drop_index('ix_scraped_characters_id', table_name='scraped_characters')
    op.drop_index('ix_scraped_characters_name', table_name='scraped_characters')
    op.drop_table('scraped_characters')
    op.add_column('characters', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('characters', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('characters', 'last_seen_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('last_seen_location', sa.VARCHAR(), nullable=True))
    op.drop_column('characters', 'updated_at')
    op.drop_column('characters', 'created_at')
    op.create_table('scraped_characters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('sex', sa.VARCHAR(), nullable=True),
    sa.Column('vocation', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('world', sa.VARCHAR(), nullable=True),
    sa.Column('residence', sa.VARCHAR(), nullable=True),
    sa.Column('house', sa.VARCHAR(), nullable=True),
    sa.Column('guild_membership', sa.VARCHAR(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('account_status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scraped_characters_name', 'scraped_characters', ['name'], unique=1)
    op.create_index('ix_scraped_characters_id', 'scraped_characters', ['id'], unique=False)
    op.create_table('enemy_characters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character_name', sa.VARCHAR(), nullable=True),
    sa.Column('vocation', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.Column('last_seen_online', sa.DATETIME(), nullable=True),
    sa.Column('last_seen_location', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enemy_characters_id', 'enemy_characters', ['id'], unique=False)
    op.create_index('ix_enemy_characters_character_name', 'enemy_characters', ['character_name'], unique=1)
    # ### end Alembic commands ###
