"""Add reason row to enemy_characters table

Revision ID: 52d6b303fe59
Revises: a737ee5f679f
Create Date: 2025-05-16 02:50:00.661293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d6b303fe59'
down_revision: Union[str, None] = 'a737ee5f679f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enemy_characters', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enemy_characters', 'reason')
    # ### end Alembic commands ###
