"""add_character_details_columns

Revision ID: 688220781b68
Revises: 8b51699030e4
Create Date: 2025-04-22 04:10:10.431956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688220781b68'
down_revision: Union[str, None] = '8b51699030e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('sex', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('vocation', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('world', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('residence', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('house', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('guild_membership', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'guild_membership')
    op.drop_column('characters', 'house')
    op.drop_column('characters', 'residence')
    op.drop_column('characters', 'world')
    op.drop_column('characters', 'level')
    op.drop_column('characters', 'vocation')
    op.drop_column('characters', 'sex')
    # ### end Alembic commands ###
