"""add_character_details_columns

Revision ID: 6e766aa2f83f
Revises: 688220781b68
Create Date: 2025-04-22 04:35:18.470736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e766aa2f83f'
down_revision: Union[str, None] = '688220781b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('account_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'account_status')
    op.drop_column('characters', 'comment')
    # ### end Alembic commands ###
